### ISSUE TITLE
[Feature request] Add QR to README

### ISSUE THREAD

**Issue by git-toni** [aalises/bicing-nearest-station-app#1]
Great app! :biking_man: :heart: 
Couldn't find it in Expo gallery.
It'd be great to test it on the phone via QR if it's eventually deployed. thx! :)

**Comment by aalises** [comment]
Hello @git-toni !! Sorry, I just saw this 😆 , it's published here https://expo.io/@yorkeutopy/bicing-nearest-station-app . Added the link on the README as well!
